import type { IntegrationConfigValues } from "@/src/services/integrationStore";

function boolValue(value: string | boolean | undefined, fallback: boolean): boolean {
  if (typeof value === "boolean") return value;
  if (typeof value === "string") {
    const lower = value.toLowerCase();
    if (lower === "true") return true;
    if (lower === "false") return false;
  }
  return fallback;
}

function asString(value: string | boolean | undefined, fallback: string): string {
  if (typeof value === "string" && value.trim()) return value.trim();
  return fallback;
}

export function generateGithubActionsWorkflow(config: IntegrationConfigValues): string {
  const repository = asString(config.repository, "org/repo");
  const workflowFile = asString(config.workflow_file, ".github/workflows/ai-governance.yml");
  const blockOnPolicyFailure = boolValue(config.block_on_policy_failure, true);

  const GH_EVENT_NAME = "${{ github.event_name }}";
  const GH_BASE_SHA = "${{ github.event.pull_request.base.sha }}";
  const GH_SHA = "${{ github.sha }}";
  const GH_BEFORE = "${{ github.event.before }}";
  const GH_CHANGED_FILES = "${{ steps.changed.outputs.files }}";
  const GH_SECRET_API_URL = "${{ secrets.AI_GOVERNANCE_API_URL }}";
  const GH_SECRET_API_KEY = "${{ secrets.AI_GOVERNANCE_API_KEY }}";
  const GH_GITHUB_TOKEN = "${{ secrets.GITHUB_TOKEN }}";
  const GH_DENY_COUNT = "${{ steps.simulate.outputs.deny_count }}";

  return `# Generated by AI Governance Integrations Marketplace
# Save as ${workflowFile}
name: AI Governance Policy Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  policy-check:
    name: AI Governance Policy Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Collect changed files
        id: changed
        run: |
          if [ "${GH_EVENT_NAME}" = "pull_request" ]; then
            git diff --name-only ${GH_BASE_SHA}...${GH_SHA} > changed_files.txt
          else
            git diff --name-only ${GH_BEFORE}...${GH_SHA} > changed_files.txt
          fi
          echo "files=$(tr '\n' ',' < changed_files.txt | sed 's/,$//')" >> $GITHUB_OUTPUT

      - name: Run policy simulation
        id: simulate
        env:
          AGENTGATE_API_URL: ${GH_SECRET_API_URL}
          AGENTGATE_API_KEY: ${GH_SECRET_API_KEY}
        run: |
          CHANGED_FILES="${GH_CHANGED_FILES}"
          RESPONSE=$(curl -sS -X POST "$AGENTGATE_API_URL/simulations/policy-check" \
            -H "Authorization: Bearer $AGENTGATE_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"repository\": \"${repository}\", \"ref\": \"${GH_SHA}\", \"changed_files\": \"$CHANGED_FILES\"}")

          echo "$RESPONSE" > simulation.json
          DENY_COUNT=$(jq '[.decisions[] | select(.decision == "DENY")] | length' simulation.json)
          echo "deny_count=$DENY_COUNT" >> $GITHUB_OUTPUT

          TABLE_HEADER='| Policy | Result | Reason |\n|---|---|---|'
          TABLE_ROWS=$(jq -r '.decisions[] | "| \(.policy_name) | \(.decision) | \(.reason // \"\") |"' simulation.json)
          printf "%b\n%b\n" "$TABLE_HEADER" "$TABLE_ROWS" > comment.md

      - name: Comment policy summary on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${GH_GITHUB_TOKEN}
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('comment.md', 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '## AI Governance Policy Simulation\\n\\n' + body
            });

      - name: Enforce policy decision
        if: ${blockOnPolicyFailure ? "always()" : "false"}
        run: |
          if [ "${GH_DENY_COUNT}" -gt 0 ]; then
            echo "DENY decisions detected (${GH_DENY_COUNT}). Blocking merge."
            exit 1
          fi

  policy-deploy:
    name: Deploy policy on main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: policy-check
    runs-on: ubuntu-latest
    steps:
      - name: Trigger policy deployment
        env:
          AGENTGATE_API_URL: ${GH_SECRET_API_URL}
          AGENTGATE_API_KEY: ${GH_SECRET_API_KEY}
        run: |
          curl -sS -X POST "$AGENTGATE_API_URL/policies/deploy" \
            -H "Authorization: Bearer $AGENTGATE_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"repository\": \"${repository}\", \"source\": \"github-actions\", \"sha\": \"${GH_SHA}\"}"
`;
}

export function suggestedWorkflowPath(config: IntegrationConfigValues): string {
  return asString(config.workflow_file, ".github/workflows/ai-governance.yml");
}
