import type { Incident, IncidentSeverity } from "@/src/types/incident";

type JiraCreateResult = {
  success: boolean;
  issueKey: string | null;
  error?: string;
};

export type JiraConfigOverrides = {
  domain?: string;
  email?: string;
  api_token?: string;
  project_key?: string;
  incident_issue_type?: string;
  agent_field_id?: string;
};

function envValue(key: string): string {
  if (typeof process === "undefined") return "";
  return (process.env[key] ?? "").trim();
}

function isMockIntegrations(): boolean {
  const raw =
    envValue("NEXT_PUBLIC_MOCK_INTEGRATIONS") ||
    envValue("VITE_MOCK_INTEGRATIONS") ||
    "true";
  return raw.toLowerCase() === "true";
}

function jiraPriority(severity: IncidentSeverity): string {
  if (severity === "CRITICAL") return "Highest";
  if (severity === "HIGH") return "High";
  if (severity === "MEDIUM") return "Medium";
  return "Low";
}

function normalizeJiraDomain(raw: string): string {
  const trimmed = raw.trim();
  if (!trimmed) return "";

  try {
    if (trimmed.startsWith("http://") || trimmed.startsWith("https://")) {
      return new URL(trimmed).host;
    }
  } catch {
    return trimmed.replace(/^https?:\/\//, "").replace(/\/+$/, "");
  }

  const withoutScheme = trimmed.replace(/^https?:\/\//, "").replace(/\/+$/, "");
  if (!withoutScheme.includes(".")) {
    return `${withoutScheme}.atlassian.net`;
  }
  return withoutScheme;
}

function tableRow(label: string, value: string) {
  return {
    type: "tableRow",
    content: [
      {
        type: "tableCell",
        content: [{ type: "paragraph", content: [{ type: "text", text: label }] }],
      },
      {
        type: "tableCell",
        content: [{ type: "paragraph", content: [{ type: "text", text: value }] }],
      },
    ],
  };
}

function incidentToAdf(incident: Incident) {
  return {
    type: "doc",
    version: 1,
    content: [
      {
        type: "paragraph",
        content: [{ type: "text", text: "Auto-generated by AI Governance Platform" }],
      },
      {
        type: "table",
        attrs: { isNumberColumnEnabled: false, layout: "default" },
        content: [
          tableRow("Incident ID", incident.id),
          tableRow("Title", incident.title),
          tableRow("Severity", incident.severity),
          tableRow("Status", incident.status),
          tableRow("Agent ID", incident.triggered_by.agent_id),
          tableRow("Action Type", incident.triggered_by.action_type),
          tableRow("Risk Score", String(incident.triggered_by.risk_score)),
          tableRow("Policy Triggered", incident.triggered_by.policy_triggered),
          tableRow("Created At", incident.created_at),
        ],
      },
    ],
  };
}

export async function createJiraIssue(
  incident: Incident,
  overrides: JiraConfigOverrides = {},
): Promise<JiraCreateResult> {
  const mock = isMockIntegrations();

  const domain = normalizeJiraDomain(
    overrides.domain ||
      envValue("NEXT_PUBLIC_JIRA_DOMAIN") ||
      envValue("VITE_JIRA_DOMAIN"),
  );
  const projectKey =
    overrides.project_key ||
    envValue("NEXT_PUBLIC_JIRA_PROJECT_KEY") ||
    envValue("VITE_JIRA_PROJECT_KEY");
  const authEmail =
    overrides.email ||
    envValue("NEXT_PUBLIC_JIRA_EMAIL") ||
    envValue("VITE_JIRA_EMAIL");
  const apiToken =
    overrides.api_token ||
    envValue("NEXT_PUBLIC_JIRA_API_TOKEN") ||
    envValue("VITE_JIRA_API_TOKEN");
  const agentFieldId =
    overrides.agent_field_id ||
    envValue("NEXT_PUBLIC_JIRA_AGENT_FIELD_ID") ||
    envValue("VITE_JIRA_AGENT_FIELD_ID");
  const issueType = overrides.incident_issue_type || "Security Incident";

  if (mock) {
    const issueKey = `${projectKey || "SEC"}-${Math.floor(Math.random() * 900 + 100)}`;
    console.log("[jiraService] MOCK create issue", { issueKey, incidentId: incident.id });
    return { success: true, issueKey };
  }

  if (!domain || !projectKey || !authEmail || !apiToken) {
    return {
      success: false,
      issueKey: null,
      error: "Missing Jira configuration: JIRA_DOMAIN/JIRA_PROJECT_KEY/JIRA_EMAIL/JIRA_API_TOKEN",
    };
  }

  try {
    const url = `https://${domain}/rest/api/3/issue`;
    const customAgentField = agentFieldId
      ? { [agentFieldId]: incident.triggered_by.agent_id }
      : {};

    const body = {
      fields: {
        project: { key: projectKey },
        issuetype: { name: issueType },
        summary: incident.title,
        priority: { name: jiraPriority(incident.severity) },
        description: incidentToAdf(incident),
        labels: ["ai-governance", "auto-generated"],
        ...customAgentField,
      },
    };

    const basic = btoa(`${authEmail}:${apiToken}`);
    const response = await fetch(url, {
      method: "POST",
      headers: {
        Authorization: `Basic ${basic}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      const text = await response.text();
      return { success: false, issueKey: null, error: `Jira HTTP ${response.status}: ${text}` };
    }

    const data = (await response.json()) as { key?: string };
    return { success: true, issueKey: data.key ?? null };
  } catch (error) {
    return {
      success: false,
      issueKey: null,
      error: error instanceof Error ? error.message : "Unknown Jira error",
    };
  }
}

const MOCK_DONE_KEY = "agentgate_mock_jira_done_keys";

export function markMockJiraDone(issueKey: string): void {
  const raw = localStorage.getItem(MOCK_DONE_KEY);
  const keys = raw ? (JSON.parse(raw) as string[]) : [];
  if (!keys.includes(issueKey)) keys.push(issueKey);
  localStorage.setItem(MOCK_DONE_KEY, JSON.stringify(keys));
}

export async function syncJiraDoneStatuses(issueKeys: string[]): Promise<string[]> {
  const mock = isMockIntegrations();
  if (mock) {
    const raw = localStorage.getItem(MOCK_DONE_KEY);
    const done = new Set(raw ? (JSON.parse(raw) as string[]) : []);
    return issueKeys.filter((key) => done.has(key));
  }

  const domain = envValue("NEXT_PUBLIC_JIRA_DOMAIN") || envValue("VITE_JIRA_DOMAIN");
  const authEmail = envValue("NEXT_PUBLIC_JIRA_EMAIL") || envValue("VITE_JIRA_EMAIL");
  const apiToken = envValue("NEXT_PUBLIC_JIRA_API_TOKEN") || envValue("VITE_JIRA_API_TOKEN");

  if (!domain || !authEmail || !apiToken) return [];

  const basic = btoa(`${authEmail}:${apiToken}`);
  const done: string[] = [];

  for (const key of issueKeys) {
    try {
      const url = `https://${domain}.atlassian.net/rest/api/3/issue/${key}?fields=status`;
      const response = await fetch(url, {
        headers: { Authorization: `Basic ${basic}` },
      });
      if (!response.ok) continue;
      const data = (await response.json()) as { fields?: { status?: { name?: string } } };
      const status = data.fields?.status?.name?.toLowerCase() ?? "";
      if (status === "done") done.push(key);
    } catch {
      continue;
    }
  }

  return done;
}
